### PR TITLE
Add additional games I own.

### PR DESCRIPTION
**Pull request by drewthatgamer**
Just added a couple games that I happen to own.

### CODE REVIEW

**Comment by chris062689** [comment]
Please correct these build errors. Thanks.

**Comment by drewthatgamer** [comment]
build errors have been fixed @chris062689

**Comment by drewthatgamer** [comment]
games haven't shown up yet on website. Just wondering if the website must be updated first, or if I did something wrong.

**Comment by j-selby** [comment]
@drewthatgamer games can take up to 24 hours to appear. Please be patient.

**Comment by drewthatgamer** [comment]
Oh, sorry. Was just worried I messed up :/

**Pull request merged**
