### PR TITLE
Fix broken folders part 2

### PR DESCRIPTION
**Pull request by FearlessTobi**
[**Part of the Games DB Overhauling**]

* Fixed broken folders & wiki pages for the following games :
```
3d-kirbys-adventure ->                              3d-classics-kirbys-adventure
legend-of-dark-witch ->                             the-legend-of-dark-witch
legend-of-zelda-majoras-mask ->                     the-legend-of-zelda-majoras-mask-3d
legend-of-zelda-ocarina-of-time ->                  the-legend-of-zelda-ocarina-of-time-3d
legend-of-zelda ->                                  the-legend-of-zelda
legend-of-zelda-a-link-between-worlds ->            the-legend-of-zelda-a-link-between-worlds
legend-of-legacy ->                                 the-legend-of-legacy
legend-of-dark-witch-2-the-price-of-desire ->       the-legend-of-dark-witch-2
super-pokemon-rumble ->                             pokemon-rumble-blast
ttf-curtain-call ->                                 theatrhythm-final-fantasy-curtain-call
yo-kai-watch-2 ->                                   yo-kai-watch-2-psychic-specters
laytons-mystery-journey-update-ver-12 ->            laytons-mystery-journey
mario-and-luigi-dream-team-update ->                mario-and-luigi-dream-team
metroid-prime-federation-force-blast-ball-update -> metroid-prime-federation-force-blast-ball-demo
shovel-knight-treasure-trove-update-ver-32 ->       shovel-knight-treasure-trove
super-smash-bros-update-ver-117 ->                  super-smash-bros-for-nintendo-3ds
```
* The following game folders were renamed, but no wiki entries were found.
```
adventure-time-hey-ice-king ->       adventure-time-etdbidk-update-1
cn-punch-time-explosion ->           cartoon-network-punch-time-explosion
fallblox ->                          crashmo
legend-of-zelda-tri-force-heroes ->  the-legend-of-zelda-tri-force-heroes
```
* Split up the entries for the following games:
```
yo-kai-watch-blasters ->  yo-kai-watch-blasters-red-cat-corps
                          yo-kai-watch-blasters-white-dog-squad
```

### CODE REVIEW

**Comment by FearlessTobi** [comment]
I hate Windows. It made a bunch of .ini files

**DO NOT MERGE YET**

**Comment by FearlessTobi** [comment]
Problem resolved.

**Comment by chris062689** [comment]
For yo-kai-watch-blasters, they should be merged.

**Comment by FearlessTobi** [comment]
I worded this badly, if you look at the game.dat, they are already using the same wiki article.

**Comment by chris062689** [comment]
We no longer have `game.dat` entries, so these should be removed.
We should capture the Title IDs there so we can plug them into our backend.

**Comment by Developer-exe** [comment]
I'd like to point out that a directory 'project-x-zone-2' was renamed to 'project-x-zone-2-update-ver-12', which creates a conflict with a PR #544 that could otherwise be merged. Would it be better to change it back alongside the wiki entry, which was renamed for some reason too?

> from 'games/project-x-zone-2-update-ver-12' to 'games/project-x-zone-2'
> from 'wiki/project-x-zone-2-update-ver-12' to 'wiki/project-x-zone-2'

**Comment by FearlessTobi** [comment]
Any update on this?

**Comment by FearlessTobi** [comment]
Everyone is unresponsive, closing for now.

**Pull request closed without merging**
