### PR TITLE
Add Final Fantasy Explorers

### PR DESCRIPTION
**Pull request by j-selby**
Adds Final Fantasy Explorers.

*Automatically generated by PR builder*

----

Original author: @Pkhaseo - apologies, there was a bug in our PR builder -
 feel free to close https://github.com/Pkhaseo/citra-games-wiki/pull/1

### CODE REVIEW

**Comment by chris062689** [comment]
@Pkhaseo Please add a testcase.

**Comment by TheKoopaKingdom** [comment]
Pinging @Pkhaseo since the previous ones here didn't go through.

**Comment by j-selby** [comment]
No response from author - might want to close this.

**Comment by TheKoopaKingdom** [comment]
I agree, it seems their account was created for the purpose of submitting the game, and there's been no activity since.

**Pull request closed without merging**
