### PR TITLE
Add The Great Ace Attorney (Dai Gyakuten Saiban - Naruhodou Ryuunosuke no Bouken)

### PR DESCRIPTION
**Pull request by skrublordFey**
Adds The Great Ace Attorney (Dai Gyakuten Saiban - Naruhodou Ryuunosuke no Bouken).

*Automatically generated by PR builder*

### CODE REVIEW

**Comment by robzombie91** [comment]
1. The description does not need to be a whole paragraph, just describing the game's publisher and release console
2. You need at least three screenshots, i know because i have tested this game myself and it runs at a great-near perfect level

**Comment by skrublordFey** [comment]
Whoops, kinda forgot about this one, sorry. I thought I submitted 3 screenshots too, my mistake. I'll fix these issues in the coming days if not tonight, apologies for the inconvenience.

**Comment by skrublordFey** [comment]
Apologies for further questions, but are there any ways to fix these issues without resubmission? I'm new to this, so pardon my ignorance.

**Comment by robzombie91** [comment]
Change them within your repository or get a github program and use those (id recommend gitkraken since thats what i use for github)

**Comment by robzombie91** [comment]
Here is the original icon if you dont know how to remove the fan translation

https://i.imgur.com/tRw5eZE.png

**Comment by robzombie91** [comment]
https://vignette.wikia.nocookie.net/aceattorney/images/7/79/DGS_Box_art.png/revision/latest?cb=20150527150420

Link to original boxart

**Comment by robzombie91** [comment]
Succeeded by #477

**Comment by j-selby** [comment]
Closing as submitter has not replied, and #477 exists.

**Pull request closed without merging**
