### PR TITLE
Add Metroid Prime: Federation Force

### PR DESCRIPTION
**Pull request by EzekielRage**
Adds Metroid Prime: Federation Force.

*Automatically generated by PR builder*

### CODE REVIEW

**Comment by EzekielRage** [comment]
Added the wiki page (you were faster to comment on that than I was to create it XD) but how do i add more screenshots?^^

**Comment by Schplee** [comment]
LGTM, merging your first PR and the force merging this will be fine.

**Comment by Leo626** [comment]
* Please remove the LEGO screenshots.
* I also thing the issues described in the wiki should be reported and added like with LEGO PR. Other than the unnecessary LEGO screenshots, LGTM.

**Comment by EzekielRage** [comment]
I removed those hours ago when I fixed the other isuses^^

**Pull request merged**
