### PR TITLE
Tappingo Addition

### PR DESCRIPTION
**Pull request by stewartisme**

### CODE REVIEW

**Comment by chris062689** [comment]
Please correct the errors that failed the build. Seems like it's not properly parsing your images. Make sure they are in PNG format.

**Comment by Leo626** [comment]
The title id in `testcases` doesn't match any in `releases`.

**Comment by j-selby** [comment]
I think you have the wrong icon here. That looks like the icon for the sequel?

**Comment by chris062689** [comment]
@stewartisme Have a chance to review this yet? Thanks!

**Comment by chris062689** [comment]
Still pending review from @stewartisme

**Comment by stewartisme** [comment]
Sorry I missed this
It's the correct icon even though it has a 2 on it

**Comment by TheKoopaKingdom** [comment]
[Yep, that seems to be the case](https://youtu.be/EsyVl9Yno5E?t=9s). LGTM.

**Pull request merged**
