### PR TITLE
Updating Tales of the Abyss

### PR DESCRIPTION
**Pull request by jdenm8**
Update to include now no-boot state in Citra and links to the issue that causes the no-boot as reported on a different title.

### CODE REVIEW

**Comment by jdenm8** [comment]
Curious about the incomplete tag. It had a pretty huge graphical issue so I didn't think Screenshots were worth posting. 

And of course Github has added the tidying up commits from my forked repo.

**Comment by Leo626** [comment]
Huh this game regressed? I don't see how [#2543](https://github.com/citra-emu/citra/issues/2543) is related to this game. It doesn't mention it there. 

It was marked as incomplete because it lacked screenshots. It isn't required if the game doesn't boot.

**Comment by Schplee** [comment]
@Leo626 The game crashes due to the same error as [#2543](https://github.com/citra-emu/citra/issues/2543)

The game can boot, but it crashes immediately.

**Comment by jdenm8** [comment]
I'd say that the issue existed before, but it happened silently and the audio just didn't play. Now it crashes it for some reason. I've gwrittena post to put tnto the git issue thread, just haven't put it in there yet.

As for the compatible tag, it doesn't reach the menu. I'll double check what Kid Icarus Uprising has since it hangs at basically the same place, though for a different reason.

**Comment by Schplee** [comment]
Well, LGTM for the current changes. Let me know if you're going to add anything else, or it's fine to merge.

**Comment by Leo626** [comment]
LGTM

**Comment by jdenm8** [comment]
I've got nothing more to add to it at the moment. Can't add any new screenshots since it doesn't run.

**Comment by jdenm8** [comment]
I've managed to mess something up. I'll fix it.

**Pull request merged**
