### PR TITLE
Add Professor Layton and the Azran Legacy

### PR DESCRIPTION
**Pull request by Spekular**
Adds Professor Layton and the Azran Legacy.

*Automatically generated by PR builder*

### CODE REVIEW

**Comment by Spekular** [comment]
Without system files an error pops upon entering your name, but the game seems to work fine if you continue. I also can't find a title ID for australian release (November 9, 2013). I checked http://www.3dsdb.com/ and http://advanscene.com. The game doesn't appear to have alternate titles between english versions as some other Layton games have had, so that shouldn't be the issue.

**Comment by robzombie91** [comment]
boxart
Here is a shrunk png version of your boxart to reduce the file size

**Comment by Spekular** [comment]
Done. I've been using zopfli but I guess it does say to use lossy compression in the wiki.

**Comment by robzombie91** [comment]
tinypng.com

**Comment by Spekular** [comment]
Yeah, that's what I meant by "it does say to use lossy compression in the wiki". I'll remember to use that in the future, and I just made sure to do so for Scribblenauts Unlimited.

**Comment by Spekular** [comment]
needs_system_files updated!

**Pull request merged**
