### PR TITLE
Add Etrian Odyssey Untold - The Millennium Girl

### PR DESCRIPTION
**Pull request by Narihari**
Adds Etrian Odyssey Untold - The Millennium Girl.

*Automatically generated by PR builder*

### CODE REVIEW

**Comment by Narihari** [comment]
I uploaded 2 new screenshots.
screenshot_114
screenshot_115

**Comment by AuraOfTheDawn** [comment]
LGTM

**Comment by Developer-exe** [comment]
Please make sure the screenshots' names don't contain invalid characters, are lowercase only and are more brief and descriptive instead of just "Screenshot_num.png" as described in PR builder.
prbuilder

**Comment by Developer-exe** [comment]
LGTM

**Pull request merged**
