### PR TITLE
Make all game folders lowercase

### LINKED ISSUE #56: PR builder creates folders with incorrect capitalization
The PR builder used in creating a game submission from "add a game" in the game compatibility list generates a folder name using all lower case letters.

### PR DESCRIPTION
**Pull request by j-selby**
Closes #56 
This renames all game folders to be lowercase. This ensures consistency between different PRs and ensures that URLs remain uniform.

### CODE REVIEW

**Comment by Schplee** [comment]
LGTM

**Comment by Leo626** [comment]
LGTM though it needs to be rebased as there's a merge conflict.

**Comment by j-selby** [comment]
Rebased.

**Comment by TheKoopaKingdom** [comment]
LGTM.

**Pull request merged**
