### PR TITLE
Add 3 Screenshots to Animal Crossing New Leaf Folder

### PR DESCRIPTION
**Pull request by robzombie91**

### CODE REVIEW

**Comment by TheKoopaKingdom** [comment]
Are these uncompressed? It could just be me, but some of them look a bit low quality.

**Comment by robzombie91** [comment]
i had to resize them

**Comment by robzombie91** [comment]
in sharex

**Comment by TheKoopaKingdom** [comment]
Screenshots should be taken with Citra at its smallest window size, so that screenshots don't have to be resized. For more info, see [this](https://github.com/citra-emu/citra-games-wiki/blob/master/CONTRIBUTING.md#game-screenshots) section of the contributing guide.

**Comment by robzombie91** [comment]
new screens uploaded

**Pull request merged**
