### PR TITLE
Add Pokemon Rumble World

### PR DESCRIPTION
**Pull request by BreadFish64**

### CODE REVIEW

**Comment by BreadFish64** [comment]
-_- one column of pixels off

**Comment by BreadFish64** [comment]
or 11

**Comment by BreadFish64** [comment]
*flips table

**Comment by BreadFish64** [comment]
hmm one more problem

**Comment by BreadFish64** [comment]
srsly? of course that worked

**Comment by Schplee** [comment]
Looks like you finally got it right 😛 LGTM

**Comment by chris062689** [comment]
Needs one more screenshot. 

_Sent from my OnePlus ONEPLUS A3000 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by chris062689** [comment]
Needs one more screenshot.

**Pull request merged**
