### PR TITLE
Add Dragon Ball Z : Extreme Butoden

### PR DESCRIPTION
**Pull request by MojoJojoDojo**

### CODE REVIEW

**Comment by MojoJojoDojo** [comment]
phew

**Comment by MojoJojoDojo** [comment]
Still can't see it on the list.
Unless it's updated later.

**Comment by MojoJojoDojo** [comment]
How come my name is not on the testers list?
on the site.

**Comment by CodingKoopa** [comment]
Somewhat recently, we moved testcase entries to a separate internal database. Now, testcases are submitted via Citra.

**Pull request merged**
