### PR TITLE
Create Rune-Factory-4

### PR DESCRIPTION
**Pull request by tsonayoshi**
The Game.dat
title = "Rune Factory 4"
description = "Rune Factory 4is a simulation/role-playing video game developed by Neverland Co. and published by Marvelous AQL for the Nintendo 3DS. It was announced in Famitsu on June 29, 2011.[1][2] It is the sixth game in the Rune Factory series."
github_issues = [2265][]
needs_system_files = false
needs_shared_font = true
game_type = "3ds"

[[ releases ]]
title = "00040000000D2800"
region = "usa"
release_date = "2013-10-01"

[[ releases ]]
title = "00040000000D2800"
region = "eur"
release_date = "2014-12-11"

[[ releases ]]
title = "00040000000D2800"
region = "jpn"
release_date = "2012-07-19"

[[ testcases ]]
title = "00040000000D2800"
compatibility = "0"
date = "2017-06-28"
version = "HEAD-54ea95c"
author = "tsonayoshi"
cpu = "Intel Core i7-7700HQ"
gpu = "NVidia GeForce GTX 1050"
os = "Windows 10"

the icon
icon

the boxart
boxart
 
ScreenShots
b
c
a

### CODE REVIEW

**Comment by Leo626** [comment]
This is not how it should be done. Rune Factory 4 should have it's own folder. Inside should be game.dat, icon.png, boxart.png and a screenshots folder. The screenshots are not native resolution. Please see [CONTRIBUTING.md](https://github.com/citra-emu/citra-games-wiki/blob/master/CONTRIBUTING.md).

**Comment by tsonayoshi** [comment]
i made a folder but i didn"t know how to upload game.dat and the other stuff inside it ~.~

**Comment by Leo626** [comment]
You didn't create the folder, you only created a file. A simple way to do it is to create the folder in your PC with the files inside and drag and drop it into your branch if you're not familiar with github or git commands.

**Comment by Leo626** [comment]
Superseded by #36.

**Pull request closed without merging**
