### PR TITLE
Add Harvest Moon 3D: A New Beginning

### PR DESCRIPTION
**Pull request by Spekular**
Adds Harvest Moon 3D: A New Beginning.

*Automatically generated by PR builder*

### CODE REVIEW

**Comment by Spekular** [comment]
I've set the compatibility level to 4 (Intro/Menu). Technically, the intro plays and a "touch to start" screen displays that you can continue from, but it's impossible to complete character creation and into the actual game because of issues 1583 and 1980.

**Comment by Spekular** [comment]
Testcases removed, region releases added, wiki page edited. Speed % was there in response to

>Brief summary of how the game performs [including] frame rate (with general hardware comparison[)...]

I swapped fps for speed under the assumption that some games might run at 60 fps. In that case, running at 30 fps could be full speed or unplayably slow, depending on the game. I guess "frame rate" here is used more generally to mean that performance should be mentioned.

Where are you getting Title ID's from, BTW? Assuming you don't own the european and japanese version of this and checked yourself, that is. I've been grabbing it from the console, but that only lets me get the region I have.

**Comment by Leo626** [comment]
[Wikipedia page](https://en.wikipedia.org/wiki/Harvest_Moon_3D:_A_New_Beginning) has this for the release dates:

chrome_2018-02-18_14-55-54
___
Google search "3DS Title IDs". The first result is a database of most 3DS title IDs. Most games have different titles for japan releases. Harvest Moon 3D: A New Beginning for example is called Bokujō Monogatari: Hajimari no Daichi in Japan.

**Comment by Spekular** [comment]
Alright. Dates properly fixed (I looked at the page for the other game, dumb mistake). Title ID database will be useful in the future, thanks for the tip!

**Pull request merged**
