### PR TITLE
Add testcase and release to Pilotwings Resort game.dat

### PR DESCRIPTION
**Pull request by BreadFish64**
I was testing Pilotwings for the wiki article so I figured I'd add a testcase and release.

### CODE REVIEW

**Comment by Schplee** [comment]
LGTM, however, would you like to update this PR with screenshots of game play, as well as any relevant github issues? We'd like to remove the `incomplete=true` tag, and doing so would allow that.

**Comment by Schplee** [comment]
@BreadFish64 Your screenshots look great, but can you change the names? They fail the checks due to a bad character in the file name.

**Comment by BreadFish64** [comment]
Yeah I see that, gimme a second

**Comment by Schplee** [comment]
@BreadFish64 Actually, I just noticed that you're submitting this PR based on the Bleeding Edge. We only allow submissions tested via the Nightly. Please update all the information to reflect this (taking new screenshots, etc)

**Comment by BreadFish64** [comment]
*facepalm
Maybe it would be a good idea to put that in contributing.md?

**Comment by Schplee** [comment]
@BreadFish64 It doesn't say that in the contributions guide? That's incredibly strange. I've gone ahead and updated it to reflect that. Sorry for the confusion, and we appreciate your contributions 😃

**Comment by BreadFish64** [comment]
😅

**Comment by Schplee** [comment]
@BreadFish64 Your PR looks good to me, could you please remove the "incomplete=true" field entirely, and then we'll get this merged!

**Comment by j-selby** [comment]
LGTM

**Pull request merged**
