### PR TITLE
Add Rune Factory 4

### PR DESCRIPTION
**Pull request by tsonayoshi**

### CODE REVIEW

**Comment by Leo626** [comment]
- Delete the ScreenShots folder. It's causing Travis to fail.
- The first screenshot is badly cropped. Scale Citra window to its smallest size and take screenshots with ShareX.

**Comment by j-selby** [comment]
Instead of closing and reopening PRs, could you please keep all your changes in one? Thanks!

**Comment by tsonayoshi** [comment]
it keeps telling that ***Folder*** isn't supported but if i uploaded it with a new pull request it becomes accepted @.@
so it insert it in a zip file with the changes you asked for

[Rune-Factory-4.zip](https://github.com/citra-emu/citra-games-wiki/files/1116994/Rune-Factory-4.zip)

**Comment by j-selby** [comment]
A .zip is really not suitable. The Citra repository is best accessed through a dedicated Git client - there are some GUI ones with tutorials that might suit your usecase.

**Comment by tsonayoshi** [comment]
is ok now ? i finally knew how to delete files

**Comment by j-selby** [comment]
LGTM.
[Included Wiki entry](https://github.com/citra-emu/citra-games-wiki/wiki/Rune-Factory-4)

**Pull request merged**
