### PR TITLE
Add Miitopia

### PR DESCRIPTION
**Pull request by acnleditor2**
Adds Miitopia.

*Automatically generated by PR builder*

### CODE REVIEW

**Comment by acnleditor2** [comment]
Icon is uncompressed!

**Comment by Schplee** [comment]
LGTM - but will fix the boxart myself.

**Comment by acnleditor2** [comment]
New wiki

**Comment by TheKoopaKingdom** [comment]
The summary should be all one paragraph.

**Comment by acnleditor2** [comment]
Edited

**Comment by acnleditor2** [comment]
Edited :P

**Comment by Schplee** [comment]
LGTM - will fix boxart after merge.

**Pull request merged**
