### PR TITLE
Replace Miitopia boxart with an image with less artifacts

### PR DESCRIPTION
**Pull request by legoj15**
This was bugging me immensely

### CODE REVIEW

**Comment by Leo626** [comment]
Is the boxart compressed as stated in the contributing guide? I see large file size difference.

**Comment by legoj15** [comment]
Hmm, I exported it through Photoshop. I'll put it through GIMP, it has a setting for PNG compression.

**Comment by legoj15** [comment]
I was only able to bring the size down by about 20 kilobytes without sacrificing quality

**Comment by Leo626** [comment]
The guide says to use [TinyPNG](https://tinypng.com/). It could be smaller since I think the goal is to keep the repository as small as possible. Boxart quality shouldn't be a high priority.

**Comment by legoj15** [comment]
Alright, now this boxart is actually smaller than the current one, and it still looks better. I'd call that a win-win.

**Pull request merged**
